name: 'Install Dependencies'
description: 'Install dependencies'
runs:
  using: "composite"

  steps:
    - name: Clone kpsr-sdk
      uses: actions/checkout@v4
      with:
        repository: klepsydra-technologies/kpsr-sdk
        ref: main
        submodules: recursive
        path: kpsr-sdk

    - name: Build and install SDK
      shell: bash
      run: |
        mkdir build && cd build/
        cmake ..
        make -j$(nproc)
        make install
        cd ../../ && rm -rf kpsr-sdk/
      working-directory: kpsr-sdk

    - name: Clone kpsr-core
      uses: actions/checkout@v4
      with:
        repository: klepsydra-technologies/kpsr-core
        ref: main
        submodules: recursive
        path: kpsr-core

    - name: Build and install kpsr-core
      shell: bash
      run: |
        mkdir build && cd build/
        cmake -DKPSR_WITH_ZMQ=true -DKPSR_TEST_PERFORMANCE=true -DKPSR_WITH_SOCKET=true ../ 
        make -j$(nproc)
        make install
        cd ../../ && rm -rf kpsr-core/
      working-directory: kpsr-core
