# Copyright 2023 Klepsydra Technologies AG
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Code style check

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  codecoverage:
    name: Code coverage
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/klepsydra-technologies/kpsrbase:1.0.0
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build
        run: |
          python3 -m pip install build --upgrade
          python3 -m build

      - name: Coverage
        timeout-minutes: 5
        run: |
          python3 -m pip install pytest-cov==4.0.0 --upgrade
          pytest --cov=kpsr_codegen --cov-report xml:pycov.xml

      - uses: codecov/codecov-action@v3
        with:
          files: pycov.xml
